// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: proto/pk/pk.proto

// 每个 proto 文件需要定义自己的包名，类似 c++ 的名称空间。
//@common CMD_HEARTBEAT_REQ

package pk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// @msg CMD_HEARTBEAT_REPLY
// 数据结构通过 message 定义
type Hne struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 每个 message 可以有多个 field。
	// 每个 field 需要指定类型、字段名和编号。
	// Protocol Buffers 在内部使用编号区分字段，一旦指定就不能更改。
	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Hne) Reset() {
	*x = Hne{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pk_pk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hne) ProtoMessage() {}

func (x *Hne) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pk_pk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hne.ProtoReflect.Descriptor instead.
func (*Hne) Descriptor() ([]byte, []int) {
	return file_proto_pk_pk_proto_rawDescGZIP(), []int{0}
}

func (x *Hne) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_pk_pk_proto protoreflect.FileDescriptor

var file_proto_pk_pk_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6b, 0x2f, 0x70, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x6b, 0x22, 0x17, 0x0a, 0x03, 0x48, 0x6e, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d,
	0x61, 0x73, 0x73, 0x65, 0x65, 0x6c, 0x63, 0x68, 0x2f, 0x65, 0x6c, 0x6b, 0x2f, 0x74, 0x65, 0x73,
	0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_pk_pk_proto_rawDescOnce sync.Once
	file_proto_pk_pk_proto_rawDescData = file_proto_pk_pk_proto_rawDesc
)

func file_proto_pk_pk_proto_rawDescGZIP() []byte {
	file_proto_pk_pk_proto_rawDescOnce.Do(func() {
		file_proto_pk_pk_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_pk_pk_proto_rawDescData)
	})
	return file_proto_pk_pk_proto_rawDescData
}

var file_proto_pk_pk_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_pk_pk_proto_goTypes = []any{
	(*Hne)(nil), // 0: pk.Hne
}
var file_proto_pk_pk_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_pk_pk_proto_init() }
func file_proto_pk_pk_proto_init() {
	if File_proto_pk_pk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_pk_pk_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Hne); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_pk_pk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_pk_pk_proto_goTypes,
		DependencyIndexes: file_proto_pk_pk_proto_depIdxs,
		MessageInfos:      file_proto_pk_pk_proto_msgTypes,
	}.Build()
	File_proto_pk_pk_proto = out.File
	file_proto_pk_pk_proto_rawDesc = nil
	file_proto_pk_pk_proto_goTypes = nil
	file_proto_pk_pk_proto_depIdxs = nil
}
