// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * coderx
 * coderx server
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GithubComChamElkPkgOvError,
  GithubComChamElkPkgOvLoginRequest,
  GithubComChamElkPkgOvRegisterReq,
  GithubComChamElkPkgOvRegisterResp,
  GithubComChamElkPkgOvToken,
} from '../models/index';
import {
    GithubComChamElkPkgOvErrorFromJSON,
    GithubComChamElkPkgOvErrorToJSON,
    GithubComChamElkPkgOvLoginRequestFromJSON,
    GithubComChamElkPkgOvLoginRequestToJSON,
    GithubComChamElkPkgOvRegisterReqFromJSON,
    GithubComChamElkPkgOvRegisterReqToJSON,
    GithubComChamElkPkgOvRegisterRespFromJSON,
    GithubComChamElkPkgOvRegisterRespToJSON,
    GithubComChamElkPkgOvTokenFromJSON,
    GithubComChamElkPkgOvTokenToJSON,
} from '../models/index';

export interface ApiAuthLoginPostRequest {
    body: GithubComChamElkPkgOvLoginRequest;
}

export interface ApiAuthRefreshTokenPostRequest {
    body: GithubComChamElkPkgOvRegisterReq;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * 登陆
     * 登陆
     */
    async apiAuthLoginPostRaw(requestParameters: ApiAuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GithubComChamElkPkgOvToken>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiAuthLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GithubComChamElkPkgOvLoginRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GithubComChamElkPkgOvTokenFromJSON(jsonValue));
    }

    /**
     * 登陆
     * 登陆
     */
    async apiAuthLoginPost(requestParameters: ApiAuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GithubComChamElkPkgOvToken> {
        const response = await this.apiAuthLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 登出
     * 登出
     */
    async apiAuthLogoutPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/auth/logout`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 登出
     * 登出
     */
    async apiAuthLogoutPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiAuthLogoutPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * register
     * register
     */
    async apiAuthRefreshTokenPostRaw(requestParameters: ApiAuthRefreshTokenPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GithubComChamElkPkgOvRegisterResp>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiAuthRefreshTokenPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/auth/refresh_token`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GithubComChamElkPkgOvRegisterReqToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GithubComChamElkPkgOvRegisterRespFromJSON(jsonValue));
    }

    /**
     * register
     * register
     */
    async apiAuthRefreshTokenPost(requestParameters: ApiAuthRefreshTokenPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GithubComChamElkPkgOvRegisterResp> {
        const response = await this.apiAuthRefreshTokenPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
