/* tslint:disable */
/* eslint-disable */
/**
 * Calculator Service
 * Service for multiplying numbers, a Goa teaser
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface CalcMultiplyRequest {
    a: number;
    b: number;
}

/**
 * 
 */
export class CalcApi extends runtime.BaseAPI {

    /**
     * multiply calc
     */
    async calcMultiplyRaw(requestParameters: CalcMultiplyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        if (requestParameters['a'] == null) {
            throw new runtime.RequiredError(
                'a',
                'Required parameter "a" was null or undefined when calling calcMultiply().'
            );
        }

        if (requestParameters['b'] == null) {
            throw new runtime.RequiredError(
                'b',
                'Required parameter "b" was null or undefined when calling calcMultiply().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/multiply/{a}/{b}`.replace(`{${"a"}}`, encodeURIComponent(String(requestParameters['a']))).replace(`{${"b"}}`, encodeURIComponent(String(requestParameters['b']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * multiply calc
     */
    async calcMultiply(requestParameters: CalcMultiplyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.calcMultiplyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
