// @ts-nocheck
// @ts-nocheck
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CoderX Service
 * Service for code generation and management
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LoginRequestBody,
  LoginResult,
  User,
} from '../models/index';
import {
    LoginRequestBodyFromJSON,
    LoginRequestBodyToJSON,
    LoginResultFromJSON,
    LoginResultToJSON,
    UserFromJSON,
    UserToJSON,
} from '../models/index';

export interface LoginLoginRequest {
    loginRequestBody: LoginRequestBody;
}

/**
 * 
 */
export class LoginApi extends runtime.BaseAPI {

    /**
     * currentUser login
     */
    async loginCurrentUserRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_header_Authorization", ["api:access"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/current-user`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * currentUser login
     */
    async loginCurrentUser(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.loginCurrentUserRaw(initOverrides);
        return await response.value();
    }

    /**
     * login login
     */
    async loginLoginRaw(requestParameters: LoginLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginResult>> {
        if (requestParameters['loginRequestBody'] == null) {
            throw new runtime.RequiredError(
                'loginRequestBody',
                'Required parameter "loginRequestBody" was null or undefined when calling loginLogin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestBodyToJSON(requestParameters['loginRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginResultFromJSON(jsonValue));
    }

    /**
     * login login
     */
    async loginLogin(requestParameters: LoginLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginResult> {
        const response = await this.loginLoginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * logout login
     */
    async loginLogoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_header_Authorization", ["api:access"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/logout`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * logout login
     */
    async loginLogout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.loginLogoutRaw(initOverrides);
    }

}
