// @ts-nocheck
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CoderX Service
 * Service for code generation and management
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalyzeCodeRequestBody
 */
export interface AnalyzeCodeRequestBody {
    /**
     * Code to analyze
     * @type {string}
     * @memberof AnalyzeCodeRequestBody
     */
    code: string;
}

/**
 * Check if a given object implements the AnalyzeCodeRequestBody interface.
 */
export function instanceOfAnalyzeCodeRequestBody(value: object): value is AnalyzeCodeRequestBody {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function AnalyzeCodeRequestBodyFromJSON(json: any): AnalyzeCodeRequestBody {
    return AnalyzeCodeRequestBodyFromJSONTyped(json, false);
}

export function AnalyzeCodeRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyzeCodeRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function AnalyzeCodeRequestBodyToJSON(value?: AnalyzeCodeRequestBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
    };
}

