// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * coderx
 * coderx server
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GithubComChamElkInternalModelSystemSystem } from './GithubComChamElkInternalModelSystemSystem';
import {
    GithubComChamElkInternalModelSystemSystemFromJSON,
    GithubComChamElkInternalModelSystemSystemFromJSONTyped,
    GithubComChamElkInternalModelSystemSystemToJSON,
} from './GithubComChamElkInternalModelSystemSystem';

/**
 * 
 * @export
 * @interface ApiSystemsPost200Response
 */
export interface ApiSystemsPost200Response {
    /**
     * 
     * @type {number}
     * @memberof ApiSystemsPost200Response
     */
    code?: number;
    /**
     * 
     * @type {GithubComChamElkInternalModelSystemSystem}
     * @memberof ApiSystemsPost200Response
     */
    data?: GithubComChamElkInternalModelSystemSystem;
    /**
     * 
     * @type {string}
     * @memberof ApiSystemsPost200Response
     */
    msg?: string;
}

/**
 * Check if a given object implements the ApiSystemsPost200Response interface.
 */
export function instanceOfApiSystemsPost200Response(value: object): value is ApiSystemsPost200Response {
    return true;
}

export function ApiSystemsPost200ResponseFromJSON(json: any): ApiSystemsPost200Response {
    return ApiSystemsPost200ResponseFromJSONTyped(json, false);
}

export function ApiSystemsPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSystemsPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : GithubComChamElkInternalModelSystemSystemFromJSON(json['data']),
        'msg': json['msg'] == null ? undefined : json['msg'],
    };
}

export function ApiSystemsPost200ResponseToJSON(value?: ApiSystemsPost200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'data': GithubComChamElkInternalModelSystemSystemToJSON(value['data']),
        'msg': value['msg'],
    };
}

