// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * coderx
 * coderx server
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GithubComChamElkInternalModelSystemSystem } from './GithubComChamElkInternalModelSystemSystem';
import {
    GithubComChamElkInternalModelSystemSystemFromJSON,
    GithubComChamElkInternalModelSystemSystemFromJSONTyped,
    GithubComChamElkInternalModelSystemSystemToJSON,
} from './GithubComChamElkInternalModelSystemSystem';

/**
 * 
 * @export
 * @interface ApiSystemsGet200Response
 */
export interface ApiSystemsGet200Response {
    /**
     * 
     * @type {number}
     * @memberof ApiSystemsGet200Response
     */
    code?: number;
    /**
     * 
     * @type {Array<GithubComChamElkInternalModelSystemSystem>}
     * @memberof ApiSystemsGet200Response
     */
    data?: Array<GithubComChamElkInternalModelSystemSystem>;
    /**
     * 
     * @type {string}
     * @memberof ApiSystemsGet200Response
     */
    msg?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiSystemsGet200Response
     */
    total?: number;
}

/**
 * Check if a given object implements the ApiSystemsGet200Response interface.
 */
export function instanceOfApiSystemsGet200Response(value: object): value is ApiSystemsGet200Response {
    return true;
}

export function ApiSystemsGet200ResponseFromJSON(json: any): ApiSystemsGet200Response {
    return ApiSystemsGet200ResponseFromJSONTyped(json, false);
}

export function ApiSystemsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSystemsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(GithubComChamElkInternalModelSystemSystemFromJSON)),
        'msg': json['msg'] == null ? undefined : json['msg'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function ApiSystemsGet200ResponseToJSON(value?: ApiSystemsGet200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(GithubComChamElkInternalModelSystemSystemToJSON)),
        'msg': value['msg'],
        'total': value['total'],
    };
}

