/* tslint:disable */
/* eslint-disable */
/**
 * Calculator Service
 * Service for multiplying numbers, a Goa teaser
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Create
 */
export interface Create {
    /**
     * Href of the created resource
     * @type {string}
     * @memberof Create
     */
    href?: string;
    /**
     * Name of the created resource
     * @type {string}
     * @memberof Create
     */
    name?: string;
}

/**
 * Check if a given object implements the Create interface.
 */
export function instanceOfCreate(value: object): value is Create {
    return true;
}

export function CreateFromJSON(json: any): Create {
    return CreateFromJSONTyped(json, false);
}

export function CreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): Create {
    if (json == null) {
        return json;
    }
    return {
        
        'href': json['href'] == null ? undefined : json['href'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function CreateToJSON(value?: Create | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'href': value['href'],
        'name': value['name'],
    };
}

