// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * coderx
 * coderx server
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GithubComChamElkPkgOvError
 */
export interface GithubComChamElkPkgOvError {
    /**
     * 
     * @type {number}
     * @memberof GithubComChamElkPkgOvError
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof GithubComChamElkPkgOvError
     */
    message?: string;
}

/**
 * Check if a given object implements the GithubComChamElkPkgOvError interface.
 */
export function instanceOfGithubComChamElkPkgOvError(value: object): value is GithubComChamElkPkgOvError {
    return true;
}

export function GithubComChamElkPkgOvErrorFromJSON(json: any): GithubComChamElkPkgOvError {
    return GithubComChamElkPkgOvErrorFromJSONTyped(json, false);
}

export function GithubComChamElkPkgOvErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubComChamElkPkgOvError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GithubComChamElkPkgOvErrorToJSON(value?: GithubComChamElkPkgOvError | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

