// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * coderx
 * coderx server
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GormDeletedAt } from './GormDeletedAt';
import {
    GormDeletedAtFromJSON,
    GormDeletedAtFromJSONTyped,
    GormDeletedAtToJSON,
} from './GormDeletedAt';

/**
 * 
 * @export
 * @interface GithubComChamElkInternalModelSystemSystem
 */
export interface GithubComChamElkInternalModelSystemSystem {
    /**
     * 
     * @type {string}
     * @memberof GithubComChamElkInternalModelSystemSystem
     */
    config?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComChamElkInternalModelSystemSystem
     */
    createdAt?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof GithubComChamElkInternalModelSystemSystem
     */
    deletedAt?: GormDeletedAt;
    /**
     * 
     * @type {number}
     * @memberof GithubComChamElkInternalModelSystemSystem
     */
    id?: number;
    /**
     * 备注
     * @type {string}
     * @memberof GithubComChamElkInternalModelSystemSystem
     */
    remark?: string;
    /**
     * 系统状态，如：1表示运行中，0表示停止
     * @type {number}
     * @memberof GithubComChamElkInternalModelSystemSystem
     */
    status?: number;
    /**
     * 系统类型，如：elk
     * @type {string}
     * @memberof GithubComChamElkInternalModelSystemSystem
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComChamElkInternalModelSystemSystem
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the GithubComChamElkInternalModelSystemSystem interface.
 */
export function instanceOfGithubComChamElkInternalModelSystemSystem(value: object): value is GithubComChamElkInternalModelSystemSystem {
    return true;
}

export function GithubComChamElkInternalModelSystemSystemFromJSON(json: any): GithubComChamElkInternalModelSystemSystem {
    return GithubComChamElkInternalModelSystemSystemFromJSONTyped(json, false);
}

export function GithubComChamElkInternalModelSystemSystemFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubComChamElkInternalModelSystemSystem {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : json['config'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'deletedAt': json['deletedAt'] == null ? undefined : GormDeletedAtFromJSON(json['deletedAt']),
        'id': json['id'] == null ? undefined : json['id'],
        'remark': json['remark'] == null ? undefined : json['remark'],
        'status': json['status'] == null ? undefined : json['status'],
        'type': json['type'] == null ? undefined : json['type'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
    };
}

export function GithubComChamElkInternalModelSystemSystemToJSON(value?: GithubComChamElkInternalModelSystemSystem | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'config': value['config'],
        'createdAt': value['createdAt'],
        'deletedAt': GormDeletedAtToJSON(value['deletedAt']),
        'id': value['id'],
        'remark': value['remark'],
        'status': value['status'],
        'type': value['type'],
        'updatedAt': value['updatedAt'],
    };
}

