// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * coderx
 * coderx server
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GithubComChamElkPkgOvRegisterResp
 */
export interface GithubComChamElkPkgOvRegisterResp {
    /**
     * 
     * @type {string}
     * @memberof GithubComChamElkPkgOvRegisterResp
     */
    email?: string;
    /**
     * 
     * @type {number}
     * @memberof GithubComChamElkPkgOvRegisterResp
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GithubComChamElkPkgOvRegisterResp
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComChamElkPkgOvRegisterResp
     */
    username?: string;
}

/**
 * Check if a given object implements the GithubComChamElkPkgOvRegisterResp interface.
 */
export function instanceOfGithubComChamElkPkgOvRegisterResp(value: object): value is GithubComChamElkPkgOvRegisterResp {
    return true;
}

export function GithubComChamElkPkgOvRegisterRespFromJSON(json: any): GithubComChamElkPkgOvRegisterResp {
    return GithubComChamElkPkgOvRegisterRespFromJSONTyped(json, false);
}

export function GithubComChamElkPkgOvRegisterRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubComChamElkPkgOvRegisterResp {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'id': json['id'] == null ? undefined : json['id'],
        'password': json['password'] == null ? undefined : json['password'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function GithubComChamElkPkgOvRegisterRespToJSON(value?: GithubComChamElkPkgOvRegisterResp | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'id': value['id'],
        'password': value['password'],
        'username': value['username'],
    };
}

