// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * coderx
 * coderx server
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GithubComChamElkPkgOvUser
 */
export interface GithubComChamElkPkgOvUser {
    /**
     * 
     * @type {string}
     * @memberof GithubComChamElkPkgOvUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComChamElkPkgOvUser
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComChamElkPkgOvUser
     */
    password?: string;
    /**
     * 
     * @type {number}
     * @memberof GithubComChamElkPkgOvUser
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof GithubComChamElkPkgOvUser
     */
    username?: string;
}

/**
 * Check if a given object implements the GithubComChamElkPkgOvUser interface.
 */
export function instanceOfGithubComChamElkPkgOvUser(value: object): value is GithubComChamElkPkgOvUser {
    return true;
}

export function GithubComChamElkPkgOvUserFromJSON(json: any): GithubComChamElkPkgOvUser {
    return GithubComChamElkPkgOvUserFromJSONTyped(json, false);
}

export function GithubComChamElkPkgOvUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubComChamElkPkgOvUser {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'id': json['id'] == null ? undefined : json['id'],
        'password': json['password'] == null ? undefined : json['password'],
        'status': json['status'] == null ? undefined : json['status'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function GithubComChamElkPkgOvUserToJSON(value?: GithubComChamElkPkgOvUser | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'id': value['id'],
        'password': value['password'],
        'status': value['status'],
        'username': value['username'],
    };
}

