// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * coderx
 * coderx server
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GithubComChamElkPkgOvResult
 */
export interface GithubComChamElkPkgOvResult {
    /**
     * 
     * @type {number}
     * @memberof GithubComChamElkPkgOvResult
     */
    code?: number;
    /**
     * 
     * @type {object}
     * @memberof GithubComChamElkPkgOvResult
     */
    data?: object;
    /**
     * 
     * @type {string}
     * @memberof GithubComChamElkPkgOvResult
     */
    msg?: string;
}

/**
 * Check if a given object implements the GithubComChamElkPkgOvResult interface.
 */
export function instanceOfGithubComChamElkPkgOvResult(value: object): value is GithubComChamElkPkgOvResult {
    return true;
}

export function GithubComChamElkPkgOvResultFromJSON(json: any): GithubComChamElkPkgOvResult {
    return GithubComChamElkPkgOvResultFromJSONTyped(json, false);
}

export function GithubComChamElkPkgOvResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubComChamElkPkgOvResult {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : json['data'],
        'msg': json['msg'] == null ? undefined : json['msg'],
    };
}

export function GithubComChamElkPkgOvResultToJSON(value?: GithubComChamElkPkgOvResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'data': value['data'],
        'msg': value['msg'],
    };
}

