// @ts-nocheck
// @ts-nocheck
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CoderX Service
 * Service for code generation and management
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginRequestBody
 */
export interface LoginRequestBody {
    /**
     * 密码
     * @type {string}
     * @memberof LoginRequestBody
     */
    password: string;
    /**
     * 用户名
     * @type {string}
     * @memberof LoginRequestBody
     */
    username: string;
}

/**
 * Check if a given object implements the LoginRequestBody interface.
 */
export function instanceOfLoginRequestBody(value: object): value is LoginRequestBody {
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function LoginRequestBodyFromJSON(json: any): LoginRequestBody {
    return LoginRequestBodyFromJSONTyped(json, false);
}

export function LoginRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
        'username': json['username'],
    };
}

export function LoginRequestBodyToJSON(value?: LoginRequestBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'password': value['password'],
        'username': value['username'],
    };
}

