// @ts-nocheck
// @ts-nocheck
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CoderX Service
 * Service for code generation and management
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginResult
 */
export interface LoginResult {
    /**
     * 有效时间（秒）
     * @type {number}
     * @memberof LoginResult
     */
    expiresIn: number;
    /**
     * 刷新令牌
     * @type {string}
     * @memberof LoginResult
     */
    refreshToken: string;
    /**
     * JWT令牌
     * @type {string}
     * @memberof LoginResult
     */
    token: string;
}

/**
 * Check if a given object implements the LoginResult interface.
 */
export function instanceOfLoginResult(value: object): value is LoginResult {
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function LoginResultFromJSON(json: any): LoginResult {
    return LoginResultFromJSONTyped(json, false);
}

export function LoginResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResult {
    if (json == null) {
        return json;
    }
    return {
        
        'expiresIn': json['expires_in'],
        'refreshToken': json['refresh_token'],
        'token': json['token'],
    };
}

export function LoginResultToJSON(value?: LoginResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'expires_in': value['expiresIn'],
        'refresh_token': value['refreshToken'],
        'token': value['token'],
    };
}

