// @ts-nocheck
// @ts-nocheck
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CoderX Service
 * Service for code generation and management
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OptimizeCodeRequestBody
 */
export interface OptimizeCodeRequestBody {
    /**
     * Code to optimize
     * @type {string}
     * @memberof OptimizeCodeRequestBody
     */
    code: string;
    /**
     * Optimization target (e.g., 'performance', 'memory')
     * @type {string}
     * @memberof OptimizeCodeRequestBody
     */
    target: string;
}

/**
 * Check if a given object implements the OptimizeCodeRequestBody interface.
 */
export function instanceOfOptimizeCodeRequestBody(value: object): value is OptimizeCodeRequestBody {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('target' in value) || value['target'] === undefined) return false;
    return true;
}

export function OptimizeCodeRequestBodyFromJSON(json: any): OptimizeCodeRequestBody {
    return OptimizeCodeRequestBodyFromJSONTyped(json, false);
}

export function OptimizeCodeRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptimizeCodeRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'target': json['target'],
    };
}

export function OptimizeCodeRequestBodyToJSON(value?: OptimizeCodeRequestBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'target': value['target'],
    };
}

