// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * coderx
 * coderx server
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OvToken
 */
export interface OvToken {
    /**
     * 
     * @type {number}
     * @memberof OvToken
     */
    expiresIn?: number;
    /**
     * 
     * @type {string}
     * @memberof OvToken
     */
    refreshToken?: string;
    /**
     * 
     * @type {string}
     * @memberof OvToken
     */
    token?: string;
    /**
     * 
     * @type {string}
     * @memberof OvToken
     */
    tokenType?: string;
}

/**
 * Check if a given object implements the OvToken interface.
 */
export function instanceOfOvToken(value: object): value is OvToken {
    return true;
}

export function OvTokenFromJSON(json: any): OvToken {
    return OvTokenFromJSONTyped(json, false);
}

export function OvTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): OvToken {
    if (json == null) {
        return json;
    }
    return {
        
        'expiresIn': json['expires_in'] == null ? undefined : json['expires_in'],
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
        'token': json['token'] == null ? undefined : json['token'],
        'tokenType': json['token_type'] == null ? undefined : json['token_type'],
    };
}

export function OvTokenToJSON(value?: OvToken | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'expires_in': value['expiresIn'],
        'refresh_token': value['refreshToken'],
        'token': value['token'],
        'token_type': value['tokenType'],
    };
}

