// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Calculator Service
 * Service for multiplying numbers, a Goa teaser
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateRequestBody
 */
export interface UpdateRequestBody {
    /**
     * 
     * @type {string}
     * @memberof UpdateRequestBody
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateRequestBody
     */
    name: string;
}

/**
 * Check if a given object implements the UpdateRequestBody interface.
 */
export function instanceOfUpdateRequestBody(value: object): value is UpdateRequestBody {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdateRequestBodyFromJSON(json: any): UpdateRequestBody {
    return UpdateRequestBodyFromJSONTyped(json, false);
}

export function UpdateRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'name': json['name'],
    };
}

export function UpdateRequestBodyToJSON(value?: UpdateRequestBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'name': value['name'],
    };
}

