// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/masseelch/elk/internal/client_gen/ent/collar"
	"github.com/masseelch/elk/internal/client_gen/ent/pet"
	"github.com/masseelch/elk/internal/client_gen/ent/predicate"
)

// CollarQuery is the builder for querying Collar entities.
type CollarQuery struct {
	config
	ctx        *QueryContext
	order      []collar.OrderOption
	inters     []Interceptor
	predicates []predicate.Collar
	withPet    *PetQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CollarQuery builder.
func (cq *CollarQuery) Where(ps ...predicate.Collar) *CollarQuery {
	cq.predicates = append(cq.predicates, ps...)
	return cq
}

// Limit the number of records to be returned by this query.
func (cq *CollarQuery) Limit(limit int) *CollarQuery {
	cq.ctx.Limit = &limit
	return cq
}

// Offset to start from.
func (cq *CollarQuery) Offset(offset int) *CollarQuery {
	cq.ctx.Offset = &offset
	return cq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cq *CollarQuery) Unique(unique bool) *CollarQuery {
	cq.ctx.Unique = &unique
	return cq
}

// Order specifies how the records should be ordered.
func (cq *CollarQuery) Order(o ...collar.OrderOption) *CollarQuery {
	cq.order = append(cq.order, o...)
	return cq
}

// QueryPet chains the current query on the "pet" edge.
func (cq *CollarQuery) QueryPet() *PetQuery {
	query := (&PetClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(collar.Table, collar.FieldID, selector),
			sqlgraph.To(pet.Table, pet.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, collar.PetTable, collar.PetColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Collar entity from the query.
// Returns a *NotFoundError when no Collar was found.
func (cq *CollarQuery) First(ctx context.Context) (*Collar, error) {
	nodes, err := cq.Limit(1).All(setContextOp(ctx, cq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{collar.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cq *CollarQuery) FirstX(ctx context.Context) *Collar {
	node, err := cq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Collar ID from the query.
// Returns a *NotFoundError when no Collar ID was found.
func (cq *CollarQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(1).IDs(setContextOp(ctx, cq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{collar.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cq *CollarQuery) FirstIDX(ctx context.Context) int {
	id, err := cq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Collar entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Collar entity is found.
// Returns a *NotFoundError when no Collar entities are found.
func (cq *CollarQuery) Only(ctx context.Context) (*Collar, error) {
	nodes, err := cq.Limit(2).All(setContextOp(ctx, cq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{collar.Label}
	default:
		return nil, &NotSingularError{collar.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cq *CollarQuery) OnlyX(ctx context.Context) *Collar {
	node, err := cq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Collar ID in the query.
// Returns a *NotSingularError when more than one Collar ID is found.
// Returns a *NotFoundError when no entities are found.
func (cq *CollarQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(2).IDs(setContextOp(ctx, cq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{collar.Label}
	default:
		err = &NotSingularError{collar.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cq *CollarQuery) OnlyIDX(ctx context.Context) int {
	id, err := cq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Collars.
func (cq *CollarQuery) All(ctx context.Context) ([]*Collar, error) {
	ctx = setContextOp(ctx, cq.ctx, "All")
	if err := cq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Collar, *CollarQuery]()
	return withInterceptors[[]*Collar](ctx, cq, qr, cq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cq *CollarQuery) AllX(ctx context.Context) []*Collar {
	nodes, err := cq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Collar IDs.
func (cq *CollarQuery) IDs(ctx context.Context) (ids []int, err error) {
	if cq.ctx.Unique == nil && cq.path != nil {
		cq.Unique(true)
	}
	ctx = setContextOp(ctx, cq.ctx, "IDs")
	if err = cq.Select(collar.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cq *CollarQuery) IDsX(ctx context.Context) []int {
	ids, err := cq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cq *CollarQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cq.ctx, "Count")
	if err := cq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cq, querierCount[*CollarQuery](), cq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cq *CollarQuery) CountX(ctx context.Context) int {
	count, err := cq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cq *CollarQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cq.ctx, "Exist")
	switch _, err := cq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cq *CollarQuery) ExistX(ctx context.Context) bool {
	exist, err := cq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CollarQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cq *CollarQuery) Clone() *CollarQuery {
	if cq == nil {
		return nil
	}
	return &CollarQuery{
		config:     cq.config,
		ctx:        cq.ctx.Clone(),
		order:      append([]collar.OrderOption{}, cq.order...),
		inters:     append([]Interceptor{}, cq.inters...),
		predicates: append([]predicate.Collar{}, cq.predicates...),
		withPet:    cq.withPet.Clone(),
		// clone intermediate query.
		sql:  cq.sql.Clone(),
		path: cq.path,
	}
}

// WithPet tells the query-builder to eager-load the nodes that are connected to
// the "pet" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CollarQuery) WithPet(opts ...func(*PetQuery)) *CollarQuery {
	query := (&PetClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withPet = query
	return cq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Color collar.Color `json:"color,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Collar.Query().
//		GroupBy(collar.FieldColor).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cq *CollarQuery) GroupBy(field string, fields ...string) *CollarGroupBy {
	cq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CollarGroupBy{build: cq}
	grbuild.flds = &cq.ctx.Fields
	grbuild.label = collar.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Color collar.Color `json:"color,omitempty"`
//	}
//
//	client.Collar.Query().
//		Select(collar.FieldColor).
//		Scan(ctx, &v)
func (cq *CollarQuery) Select(fields ...string) *CollarSelect {
	cq.ctx.Fields = append(cq.ctx.Fields, fields...)
	sbuild := &CollarSelect{CollarQuery: cq}
	sbuild.label = collar.Label
	sbuild.flds, sbuild.scan = &cq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CollarSelect configured with the given aggregations.
func (cq *CollarQuery) Aggregate(fns ...AggregateFunc) *CollarSelect {
	return cq.Select().Aggregate(fns...)
}

func (cq *CollarQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cq); err != nil {
				return err
			}
		}
	}
	for _, f := range cq.ctx.Fields {
		if !collar.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cq.path != nil {
		prev, err := cq.path(ctx)
		if err != nil {
			return err
		}
		cq.sql = prev
	}
	return nil
}

func (cq *CollarQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Collar, error) {
	var (
		nodes       = []*Collar{}
		withFKs     = cq.withFKs
		_spec       = cq.querySpec()
		loadedTypes = [1]bool{
			cq.withPet != nil,
		}
	)
	if cq.withPet != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, collar.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Collar).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Collar{config: cq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cq.withPet; query != nil {
		if err := cq.loadPet(ctx, query, nodes, nil,
			func(n *Collar, e *Pet) { n.Edges.Pet = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cq *CollarQuery) loadPet(ctx context.Context, query *PetQuery, nodes []*Collar, init func(*Collar), assign func(*Collar, *Pet)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Collar)
	for i := range nodes {
		if nodes[i].pet_collar == nil {
			continue
		}
		fk := *nodes[i].pet_collar
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(pet.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "pet_collar" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (cq *CollarQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cq.querySpec()
	_spec.Node.Columns = cq.ctx.Fields
	if len(cq.ctx.Fields) > 0 {
		_spec.Unique = cq.ctx.Unique != nil && *cq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cq.driver, _spec)
}

func (cq *CollarQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(collar.Table, collar.Columns, sqlgraph.NewFieldSpec(collar.FieldID, field.TypeInt))
	_spec.From = cq.sql
	if unique := cq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cq.path != nil {
		_spec.Unique = true
	}
	if fields := cq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, collar.FieldID)
		for i := range fields {
			if fields[i] != collar.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cq *CollarQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cq.driver.Dialect())
	t1 := builder.Table(collar.Table)
	columns := cq.ctx.Fields
	if len(columns) == 0 {
		columns = collar.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cq.sql != nil {
		selector = cq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cq.ctx.Unique != nil && *cq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cq.predicates {
		p(selector)
	}
	for _, p := range cq.order {
		p(selector)
	}
	if offset := cq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CollarGroupBy is the group-by builder for Collar entities.
type CollarGroupBy struct {
	selector
	build *CollarQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cgb *CollarGroupBy) Aggregate(fns ...AggregateFunc) *CollarGroupBy {
	cgb.fns = append(cgb.fns, fns...)
	return cgb
}

// Scan applies the selector query and scans the result into the given value.
func (cgb *CollarGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cgb.build.ctx, "GroupBy")
	if err := cgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CollarQuery, *CollarGroupBy](ctx, cgb.build, cgb, cgb.build.inters, v)
}

func (cgb *CollarGroupBy) sqlScan(ctx context.Context, root *CollarQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cgb.fns))
	for _, fn := range cgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cgb.flds)+len(cgb.fns))
		for _, f := range *cgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CollarSelect is the builder for selecting fields of Collar entities.
type CollarSelect struct {
	*CollarQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cs *CollarSelect) Aggregate(fns ...AggregateFunc) *CollarSelect {
	cs.fns = append(cs.fns, fns...)
	return cs
}

// Scan applies the selector query and scans the result into the given value.
func (cs *CollarSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cs.ctx, "Select")
	if err := cs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CollarQuery, *CollarSelect](ctx, cs.CollarQuery, cs, cs.inters, v)
}

func (cs *CollarSelect) sqlScan(ctx context.Context, root *CollarQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cs.fns))
	for _, fn := range cs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
