// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/masseelch/elk/internal/pets/ent/badge"
	"github.com/masseelch/elk/internal/pets/ent/pet"
	"github.com/masseelch/elk/internal/pets/ent/predicate"
)

// BadgeQuery is the builder for querying Badge entities.
type BadgeQuery struct {
	config
	ctx        *QueryContext
	order      []badge.OrderOption
	inters     []Interceptor
	predicates []predicate.Badge
	withWearer *PetQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BadgeQuery builder.
func (bq *BadgeQuery) Where(ps ...predicate.Badge) *BadgeQuery {
	bq.predicates = append(bq.predicates, ps...)
	return bq
}

// Limit the number of records to be returned by this query.
func (bq *BadgeQuery) Limit(limit int) *BadgeQuery {
	bq.ctx.Limit = &limit
	return bq
}

// Offset to start from.
func (bq *BadgeQuery) Offset(offset int) *BadgeQuery {
	bq.ctx.Offset = &offset
	return bq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bq *BadgeQuery) Unique(unique bool) *BadgeQuery {
	bq.ctx.Unique = &unique
	return bq
}

// Order specifies how the records should be ordered.
func (bq *BadgeQuery) Order(o ...badge.OrderOption) *BadgeQuery {
	bq.order = append(bq.order, o...)
	return bq
}

// QueryWearer chains the current query on the "wearer" edge.
func (bq *BadgeQuery) QueryWearer() *PetQuery {
	query := (&PetClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(badge.Table, badge.FieldID, selector),
			sqlgraph.To(pet.Table, pet.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, badge.WearerTable, badge.WearerColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Badge entity from the query.
// Returns a *NotFoundError when no Badge was found.
func (bq *BadgeQuery) First(ctx context.Context) (*Badge, error) {
	nodes, err := bq.Limit(1).All(setContextOp(ctx, bq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{badge.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bq *BadgeQuery) FirstX(ctx context.Context) *Badge {
	node, err := bq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Badge ID from the query.
// Returns a *NotFoundError when no Badge ID was found.
func (bq *BadgeQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = bq.Limit(1).IDs(setContextOp(ctx, bq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{badge.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bq *BadgeQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := bq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Badge entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Badge entity is found.
// Returns a *NotFoundError when no Badge entities are found.
func (bq *BadgeQuery) Only(ctx context.Context) (*Badge, error) {
	nodes, err := bq.Limit(2).All(setContextOp(ctx, bq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{badge.Label}
	default:
		return nil, &NotSingularError{badge.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bq *BadgeQuery) OnlyX(ctx context.Context) *Badge {
	node, err := bq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Badge ID in the query.
// Returns a *NotSingularError when more than one Badge ID is found.
// Returns a *NotFoundError when no entities are found.
func (bq *BadgeQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = bq.Limit(2).IDs(setContextOp(ctx, bq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{badge.Label}
	default:
		err = &NotSingularError{badge.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bq *BadgeQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := bq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Badges.
func (bq *BadgeQuery) All(ctx context.Context) ([]*Badge, error) {
	ctx = setContextOp(ctx, bq.ctx, "All")
	if err := bq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Badge, *BadgeQuery]()
	return withInterceptors[[]*Badge](ctx, bq, qr, bq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bq *BadgeQuery) AllX(ctx context.Context) []*Badge {
	nodes, err := bq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Badge IDs.
func (bq *BadgeQuery) IDs(ctx context.Context) (ids []uint32, err error) {
	if bq.ctx.Unique == nil && bq.path != nil {
		bq.Unique(true)
	}
	ctx = setContextOp(ctx, bq.ctx, "IDs")
	if err = bq.Select(badge.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bq *BadgeQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := bq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bq *BadgeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bq.ctx, "Count")
	if err := bq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bq, querierCount[*BadgeQuery](), bq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bq *BadgeQuery) CountX(ctx context.Context) int {
	count, err := bq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bq *BadgeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bq.ctx, "Exist")
	switch _, err := bq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bq *BadgeQuery) ExistX(ctx context.Context) bool {
	exist, err := bq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BadgeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bq *BadgeQuery) Clone() *BadgeQuery {
	if bq == nil {
		return nil
	}
	return &BadgeQuery{
		config:     bq.config,
		ctx:        bq.ctx.Clone(),
		order:      append([]badge.OrderOption{}, bq.order...),
		inters:     append([]Interceptor{}, bq.inters...),
		predicates: append([]predicate.Badge{}, bq.predicates...),
		withWearer: bq.withWearer.Clone(),
		// clone intermediate query.
		sql:  bq.sql.Clone(),
		path: bq.path,
	}
}

// WithWearer tells the query-builder to eager-load the nodes that are connected to
// the "wearer" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BadgeQuery) WithWearer(opts ...func(*PetQuery)) *BadgeQuery {
	query := (&PetClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withWearer = query
	return bq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Color badge.Color `json:"color,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Badge.Query().
//		GroupBy(badge.FieldColor).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bq *BadgeQuery) GroupBy(field string, fields ...string) *BadgeGroupBy {
	bq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BadgeGroupBy{build: bq}
	grbuild.flds = &bq.ctx.Fields
	grbuild.label = badge.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Color badge.Color `json:"color,omitempty"`
//	}
//
//	client.Badge.Query().
//		Select(badge.FieldColor).
//		Scan(ctx, &v)
func (bq *BadgeQuery) Select(fields ...string) *BadgeSelect {
	bq.ctx.Fields = append(bq.ctx.Fields, fields...)
	sbuild := &BadgeSelect{BadgeQuery: bq}
	sbuild.label = badge.Label
	sbuild.flds, sbuild.scan = &bq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BadgeSelect configured with the given aggregations.
func (bq *BadgeQuery) Aggregate(fns ...AggregateFunc) *BadgeSelect {
	return bq.Select().Aggregate(fns...)
}

func (bq *BadgeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bq); err != nil {
				return err
			}
		}
	}
	for _, f := range bq.ctx.Fields {
		if !badge.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bq.path != nil {
		prev, err := bq.path(ctx)
		if err != nil {
			return err
		}
		bq.sql = prev
	}
	return nil
}

func (bq *BadgeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Badge, error) {
	var (
		nodes       = []*Badge{}
		withFKs     = bq.withFKs
		_spec       = bq.querySpec()
		loadedTypes = [1]bool{
			bq.withWearer != nil,
		}
	)
	if bq.withWearer != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, badge.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Badge).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Badge{config: bq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bq.withWearer; query != nil {
		if err := bq.loadWearer(ctx, query, nodes, nil,
			func(n *Badge, e *Pet) { n.Edges.Wearer = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bq *BadgeQuery) loadWearer(ctx context.Context, query *PetQuery, nodes []*Badge, init func(*Badge), assign func(*Badge, *Pet)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Badge)
	for i := range nodes {
		if nodes[i].pet_badge == nil {
			continue
		}
		fk := *nodes[i].pet_badge
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(pet.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "pet_badge" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (bq *BadgeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bq.querySpec()
	_spec.Node.Columns = bq.ctx.Fields
	if len(bq.ctx.Fields) > 0 {
		_spec.Unique = bq.ctx.Unique != nil && *bq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bq.driver, _spec)
}

func (bq *BadgeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(badge.Table, badge.Columns, sqlgraph.NewFieldSpec(badge.FieldID, field.TypeUint32))
	_spec.From = bq.sql
	if unique := bq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bq.path != nil {
		_spec.Unique = true
	}
	if fields := bq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, badge.FieldID)
		for i := range fields {
			if fields[i] != badge.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := bq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bq *BadgeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bq.driver.Dialect())
	t1 := builder.Table(badge.Table)
	columns := bq.ctx.Fields
	if len(columns) == 0 {
		columns = badge.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bq.sql != nil {
		selector = bq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bq.ctx.Unique != nil && *bq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range bq.predicates {
		p(selector)
	}
	for _, p := range bq.order {
		p(selector)
	}
	if offset := bq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BadgeGroupBy is the group-by builder for Badge entities.
type BadgeGroupBy struct {
	selector
	build *BadgeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bgb *BadgeGroupBy) Aggregate(fns ...AggregateFunc) *BadgeGroupBy {
	bgb.fns = append(bgb.fns, fns...)
	return bgb
}

// Scan applies the selector query and scans the result into the given value.
func (bgb *BadgeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bgb.build.ctx, "GroupBy")
	if err := bgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BadgeQuery, *BadgeGroupBy](ctx, bgb.build, bgb, bgb.build.inters, v)
}

func (bgb *BadgeGroupBy) sqlScan(ctx context.Context, root *BadgeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bgb.fns))
	for _, fn := range bgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bgb.flds)+len(bgb.fns))
		for _, f := range *bgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BadgeSelect is the builder for selecting fields of Badge entities.
type BadgeSelect struct {
	*BadgeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bs *BadgeSelect) Aggregate(fns ...AggregateFunc) *BadgeSelect {
	bs.fns = append(bs.fns, fns...)
	return bs
}

// Scan applies the selector query and scans the result into the given value.
func (bs *BadgeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bs.ctx, "Select")
	if err := bs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BadgeQuery, *BadgeSelect](ctx, bs.BadgeQuery, bs, bs.inters, v)
}

func (bs *BadgeSelect) sqlScan(ctx context.Context, root *BadgeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bs.fns))
	for _, fn := range bs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
