// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/masseelch/elk/internal/pets/ent/pet"
	"github.com/masseelch/elk/internal/pets/ent/playgroup"
	"github.com/masseelch/elk/internal/pets/ent/predicate"
)

// PlayGroupQuery is the builder for querying PlayGroup entities.
type PlayGroupQuery struct {
	config
	ctx              *QueryContext
	order            []playgroup.OrderOption
	inters           []Interceptor
	predicates       []predicate.PlayGroup
	withParticipants *PetQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PlayGroupQuery builder.
func (pgq *PlayGroupQuery) Where(ps ...predicate.PlayGroup) *PlayGroupQuery {
	pgq.predicates = append(pgq.predicates, ps...)
	return pgq
}

// Limit the number of records to be returned by this query.
func (pgq *PlayGroupQuery) Limit(limit int) *PlayGroupQuery {
	pgq.ctx.Limit = &limit
	return pgq
}

// Offset to start from.
func (pgq *PlayGroupQuery) Offset(offset int) *PlayGroupQuery {
	pgq.ctx.Offset = &offset
	return pgq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pgq *PlayGroupQuery) Unique(unique bool) *PlayGroupQuery {
	pgq.ctx.Unique = &unique
	return pgq
}

// Order specifies how the records should be ordered.
func (pgq *PlayGroupQuery) Order(o ...playgroup.OrderOption) *PlayGroupQuery {
	pgq.order = append(pgq.order, o...)
	return pgq
}

// QueryParticipants chains the current query on the "participants" edge.
func (pgq *PlayGroupQuery) QueryParticipants() *PetQuery {
	query := (&PetClient{config: pgq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pgq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(playgroup.Table, playgroup.FieldID, selector),
			sqlgraph.To(pet.Table, pet.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, playgroup.ParticipantsTable, playgroup.ParticipantsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(pgq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PlayGroup entity from the query.
// Returns a *NotFoundError when no PlayGroup was found.
func (pgq *PlayGroupQuery) First(ctx context.Context) (*PlayGroup, error) {
	nodes, err := pgq.Limit(1).All(setContextOp(ctx, pgq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{playgroup.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pgq *PlayGroupQuery) FirstX(ctx context.Context) *PlayGroup {
	node, err := pgq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PlayGroup ID from the query.
// Returns a *NotFoundError when no PlayGroup ID was found.
func (pgq *PlayGroupQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pgq.Limit(1).IDs(setContextOp(ctx, pgq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{playgroup.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pgq *PlayGroupQuery) FirstIDX(ctx context.Context) int {
	id, err := pgq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PlayGroup entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PlayGroup entity is found.
// Returns a *NotFoundError when no PlayGroup entities are found.
func (pgq *PlayGroupQuery) Only(ctx context.Context) (*PlayGroup, error) {
	nodes, err := pgq.Limit(2).All(setContextOp(ctx, pgq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{playgroup.Label}
	default:
		return nil, &NotSingularError{playgroup.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pgq *PlayGroupQuery) OnlyX(ctx context.Context) *PlayGroup {
	node, err := pgq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PlayGroup ID in the query.
// Returns a *NotSingularError when more than one PlayGroup ID is found.
// Returns a *NotFoundError when no entities are found.
func (pgq *PlayGroupQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pgq.Limit(2).IDs(setContextOp(ctx, pgq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{playgroup.Label}
	default:
		err = &NotSingularError{playgroup.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pgq *PlayGroupQuery) OnlyIDX(ctx context.Context) int {
	id, err := pgq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PlayGroups.
func (pgq *PlayGroupQuery) All(ctx context.Context) ([]*PlayGroup, error) {
	ctx = setContextOp(ctx, pgq.ctx, "All")
	if err := pgq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PlayGroup, *PlayGroupQuery]()
	return withInterceptors[[]*PlayGroup](ctx, pgq, qr, pgq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pgq *PlayGroupQuery) AllX(ctx context.Context) []*PlayGroup {
	nodes, err := pgq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PlayGroup IDs.
func (pgq *PlayGroupQuery) IDs(ctx context.Context) (ids []int, err error) {
	if pgq.ctx.Unique == nil && pgq.path != nil {
		pgq.Unique(true)
	}
	ctx = setContextOp(ctx, pgq.ctx, "IDs")
	if err = pgq.Select(playgroup.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pgq *PlayGroupQuery) IDsX(ctx context.Context) []int {
	ids, err := pgq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pgq *PlayGroupQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pgq.ctx, "Count")
	if err := pgq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pgq, querierCount[*PlayGroupQuery](), pgq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pgq *PlayGroupQuery) CountX(ctx context.Context) int {
	count, err := pgq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pgq *PlayGroupQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pgq.ctx, "Exist")
	switch _, err := pgq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pgq *PlayGroupQuery) ExistX(ctx context.Context) bool {
	exist, err := pgq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PlayGroupQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pgq *PlayGroupQuery) Clone() *PlayGroupQuery {
	if pgq == nil {
		return nil
	}
	return &PlayGroupQuery{
		config:           pgq.config,
		ctx:              pgq.ctx.Clone(),
		order:            append([]playgroup.OrderOption{}, pgq.order...),
		inters:           append([]Interceptor{}, pgq.inters...),
		predicates:       append([]predicate.PlayGroup{}, pgq.predicates...),
		withParticipants: pgq.withParticipants.Clone(),
		// clone intermediate query.
		sql:  pgq.sql.Clone(),
		path: pgq.path,
	}
}

// WithParticipants tells the query-builder to eager-load the nodes that are connected to
// the "participants" edge. The optional arguments are used to configure the query builder of the edge.
func (pgq *PlayGroupQuery) WithParticipants(opts ...func(*PetQuery)) *PlayGroupQuery {
	query := (&PetClient{config: pgq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pgq.withParticipants = query
	return pgq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PlayGroup.Query().
//		GroupBy(playgroup.FieldTitle).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pgq *PlayGroupQuery) GroupBy(field string, fields ...string) *PlayGroupGroupBy {
	pgq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PlayGroupGroupBy{build: pgq}
	grbuild.flds = &pgq.ctx.Fields
	grbuild.label = playgroup.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//	}
//
//	client.PlayGroup.Query().
//		Select(playgroup.FieldTitle).
//		Scan(ctx, &v)
func (pgq *PlayGroupQuery) Select(fields ...string) *PlayGroupSelect {
	pgq.ctx.Fields = append(pgq.ctx.Fields, fields...)
	sbuild := &PlayGroupSelect{PlayGroupQuery: pgq}
	sbuild.label = playgroup.Label
	sbuild.flds, sbuild.scan = &pgq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PlayGroupSelect configured with the given aggregations.
func (pgq *PlayGroupQuery) Aggregate(fns ...AggregateFunc) *PlayGroupSelect {
	return pgq.Select().Aggregate(fns...)
}

func (pgq *PlayGroupQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pgq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pgq); err != nil {
				return err
			}
		}
	}
	for _, f := range pgq.ctx.Fields {
		if !playgroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pgq.path != nil {
		prev, err := pgq.path(ctx)
		if err != nil {
			return err
		}
		pgq.sql = prev
	}
	return nil
}

func (pgq *PlayGroupQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PlayGroup, error) {
	var (
		nodes       = []*PlayGroup{}
		_spec       = pgq.querySpec()
		loadedTypes = [1]bool{
			pgq.withParticipants != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PlayGroup).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PlayGroup{config: pgq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pgq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pgq.withParticipants; query != nil {
		if err := pgq.loadParticipants(ctx, query, nodes,
			func(n *PlayGroup) { n.Edges.Participants = []*Pet{} },
			func(n *PlayGroup, e *Pet) { n.Edges.Participants = append(n.Edges.Participants, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pgq *PlayGroupQuery) loadParticipants(ctx context.Context, query *PetQuery, nodes []*PlayGroup, init func(*PlayGroup), assign func(*PlayGroup, *Pet)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*PlayGroup)
	nids := make(map[int]map[*PlayGroup]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(playgroup.ParticipantsTable)
		s.Join(joinT).On(s.C(pet.FieldID), joinT.C(playgroup.ParticipantsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(playgroup.ParticipantsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(playgroup.ParticipantsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*PlayGroup]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Pet](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "participants" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (pgq *PlayGroupQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pgq.querySpec()
	_spec.Node.Columns = pgq.ctx.Fields
	if len(pgq.ctx.Fields) > 0 {
		_spec.Unique = pgq.ctx.Unique != nil && *pgq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pgq.driver, _spec)
}

func (pgq *PlayGroupQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(playgroup.Table, playgroup.Columns, sqlgraph.NewFieldSpec(playgroup.FieldID, field.TypeInt))
	_spec.From = pgq.sql
	if unique := pgq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pgq.path != nil {
		_spec.Unique = true
	}
	if fields := pgq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, playgroup.FieldID)
		for i := range fields {
			if fields[i] != playgroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pgq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pgq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pgq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pgq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pgq *PlayGroupQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pgq.driver.Dialect())
	t1 := builder.Table(playgroup.Table)
	columns := pgq.ctx.Fields
	if len(columns) == 0 {
		columns = playgroup.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pgq.sql != nil {
		selector = pgq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pgq.ctx.Unique != nil && *pgq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pgq.predicates {
		p(selector)
	}
	for _, p := range pgq.order {
		p(selector)
	}
	if offset := pgq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pgq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PlayGroupGroupBy is the group-by builder for PlayGroup entities.
type PlayGroupGroupBy struct {
	selector
	build *PlayGroupQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pggb *PlayGroupGroupBy) Aggregate(fns ...AggregateFunc) *PlayGroupGroupBy {
	pggb.fns = append(pggb.fns, fns...)
	return pggb
}

// Scan applies the selector query and scans the result into the given value.
func (pggb *PlayGroupGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pggb.build.ctx, "GroupBy")
	if err := pggb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PlayGroupQuery, *PlayGroupGroupBy](ctx, pggb.build, pggb, pggb.build.inters, v)
}

func (pggb *PlayGroupGroupBy) sqlScan(ctx context.Context, root *PlayGroupQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pggb.fns))
	for _, fn := range pggb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pggb.flds)+len(pggb.fns))
		for _, f := range *pggb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pggb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pggb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PlayGroupSelect is the builder for selecting fields of PlayGroup entities.
type PlayGroupSelect struct {
	*PlayGroupQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pgs *PlayGroupSelect) Aggregate(fns ...AggregateFunc) *PlayGroupSelect {
	pgs.fns = append(pgs.fns, fns...)
	return pgs
}

// Scan applies the selector query and scans the result into the given value.
func (pgs *PlayGroupSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pgs.ctx, "Select")
	if err := pgs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PlayGroupQuery, *PlayGroupSelect](ctx, pgs.PlayGroupQuery, pgs, pgs.inters, v)
}

func (pgs *PlayGroupSelect) sqlScan(ctx context.Context, root *PlayGroupQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pgs.fns))
	for _, fn := range pgs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pgs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pgs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
